<?php
$title = 'Sign up';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('test', array('action' => 'signupprocess')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset class="clearfix">
    <div class="frm-field-sx"><?php echo $this->formRow($form->get('firstname')); ?></div>
    <div class="frm-field-dx"><?php echo $this->formRow($form->get('surname')); ?></div>  
</fieldset>
<fieldset class="clearfix">
    <div class="frm-field-sx"><?php echo $this->formRow($form->get('email')); ?></div>
    <div class="frm-field-dx"><?php echo $this->formRow($form->get('password')); ?></div>
</fieldset>
<fieldset>
    <div id="action" class="clearfix"><?php echo $this->formSubmit($form->get('sbt-signup')); ?></div>
</fieldset>
<?php echo $this->form()->closeTag();?>
